[2024-12-26T06:16:28.913+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T06:16:29.312+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data manual__2024-12-25T15:33:13.268282+00:00 [queued]>
[2024-12-26T06:16:30.007+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data manual__2024-12-25T15:33:13.268282+00:00 [queued]>
[2024-12-26T06:16:30.107+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-26T06:16:32.007+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_produce_data> on 2024-12-25 15:33:13.268282+00:00
[2024-12-26T06:16:33.107+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=216) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-26T06:16:33.210+0000] {standard_task_runner.py:72} INFO - Started process 279 to run task
[2024-12-26T06:16:33.206+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'api_to_kafka_pipeline', 'fetch_and_produce_data', 'manual__2024-12-25T15:33:13.268282+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/api_to_kafka_dag.py', '--cfg-path', '/tmp/tmpyhxgqp1d']
[2024-12-26T06:16:33.609+0000] {standard_task_runner.py:105} INFO - Job 77: Subtask fetch_and_produce_data
[2024-12-26T06:16:35.909+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_kafka_pipeline.fetch_and_produce_data manual__2024-12-25T15:33:13.268282+00:00 [running]> on host a7d7ef0c0878
[2024-12-26T06:16:38.806+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='api_to_kafka_pipeline' AIRFLOW_CTX_TASK_ID='fetch_and_produce_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-25T15:33:13.268282+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-25T15:33:13.268282+00:00'
[2024-12-26T06:16:38.908+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T06:16:39.416+0000] {job.py:229} INFO - Heartbeat recovered after 11.61 seconds
[2024-12-26T06:16:40.106+0000] {logging_mixin.py:190} INFO - âœ… Data fetched successfully for IBM at 5min interval.
[2024-12-26T06:16:40.107+0000] {logging_mixin.py:190} INFO - ðŸš€ Sending data to Kafka...
[2024-12-26T12:29:28.481+0000] {job.py:229} INFO - Heartbeat recovered after 20483.21 seconds
[2024-12-26T13:54:42.956+0000] {job.py:229} INFO - Heartbeat recovered after 5114.58 seconds
[2024-12-26T16:09:56.080+0000] {job.py:229} INFO - Heartbeat recovered after 665.29 seconds
[2024-12-26T16:10:37.294+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-26T16:10:37.301+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-26T16:10:37.314+0000] {process_utils.py:132} INFO - Sending 15 to group 279. PIDs of all processes in the group: [279]
[2024-12-26T16:10:37.319+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 279
[2024-12-26T16:11:37.355+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=279, name='airflow task ru', status='sleeping', started='06:16:31') did not respond to SIGTERM. Trying SIGKILL
[2024-12-26T16:11:37.408+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 279
[2024-12-26T16:11:37.475+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=279, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='06:16:31') (279) terminated with exit code -9
[2024-12-26T16:11:37.478+0000] {standard_task_runner.py:190} ERROR - ('Job 77 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
